### ISSUE TITLE
Date/datetime is not supported

### ISSUE THREAD

**Issue by kohutovic** [armincms/json#1]
If I use date/datetime Nova returns: "Date field must cast to 'date' in Eloquent model.
Is there a way how to handle those field types.

**Comment by zareismail** [comment]
Hey; thanks for reporting.

This package doesn't change the default behavior of fields. so; you can use the `resolvingUsing` method for those fields like below:

```
->resolveUsing(function($value) {
       return $value ?? new \Illuminate\Support\Carbon($value);
 })
```
