### ISSUE TITLE
Array json data not working

### ISSUE THREAD

**Issue by abhitheawesomecoder** [armincms/json#11]
I have data in this format in db

[{"variation":"demo","quantity":"1","image":"abcdpic.jpg"},{"variation":"demo2","quantity":"5","image":"kkabcdpic.jpg"}]

trying to render it like 

```
Row1        variation     demo
            quantity      1
            image         abcdpic.jpg
Row2        variation     demo2
            quantity      2
            image         kkabcdpic.jpg
```

but its not working

**Comment by zareismail** [comment]
> I have data in this format in db
> 
> [{"variation":"demo","quantity":"1","image":"abcdpic.jpg"},{"variation":"demo2","quantity":"5","image":"kkabcdpic.jpg"}]
> 
> trying to render it like
> 
> ```
> Row1        variation     demo
>             quantity      1
>             image         abcdpic.jpg
> Row2        variation     demo2
>             quantity      2
>             image         kkabcdpic.jpg
> ```
> 
> but its not working

You should cast it as JSON in your model
