### ISSUE TITLE
Bug when saving

### ISSUE THREAD

**Issue by RaphaelBP** [armincms/json#4]
Hello,

Nice plugin but I have a problem when i want to save multi fields :

```php
 Json::make("Attributes2", [ 
                Text::make(__('field1')),
                Text::make(__('field2')),
                Text::make(__('field3')),
            ]),
```

Form result :
<img width="925" alt="Capture d’écran 2020-03-06 à 22 48 50" src="https://user-images.githubusercontent.com/11390378/76125287-bfa6d300-5ffc-11ea-9c61-0e55ca6bfeba.png">

When saving in database field: 

```
{"0":"{\"0\":\"{\\\"field1\\\":\\\"value1\\\"}\",\"field2\":\"value2\"}","field3":"value3"}
```

I'm using Laravel 6 and Nova 2.10.

Thanks for help.
Bye.

**Comment by zareismail** [comment]
Hi; you should cast your "Attribute2" attribute into JSON
