### ISSUE TITLE
ignoreCasting does not exist

### ISSUE THREAD

**Issue by u12206050** [armincms/json#7]
The function ignoreCasting does not exist in the latest release v0.5.1

Create a new release containing it please.

**Comment by zareismail** [comment]
Hi. thanks for reporing

use release [5.0.1](https://github.com/armincms/json/releases/tag/0.5.1)

**Comment by u12206050** [comment]
Hi, version 5.0.1 does not exist.

**Comment by zareismail** [comment]
use 0.5.2 instead of it
